### PR TITLE
Fix DelegateProxy bug

### PR DESCRIPTION
**Pull request by henrimagi**
Create a dictionary for selectors, to keep reference to all of the DelegateProxy subclass selectors.

Fixes issue #31

### CODE REVIEW

**Comment by henrimagi** [comment]
@jdisho or @freak4pc any chance having time to review it?

For a sidenote, DelegateProxy can't be fully tested using current Unit Test's. The calling mechanism is a bit more complex when it is initiated by user interaction than just calling a function of the delegate. Added some UITests's along with a ViewController to simulate a real world scenario.

What should we do with the codecov report. I think it should not include the Example project files.

**Comment by freak4pc** [comment]
I think there are enough ways to do this with regular Unit Tests, lets do no tests and I'll figure them out later. 
The only thin I'm wondering about is if it's worth moving the dictionary inside the proxy instead of having a static global. WDYT ?

**Comment by henrimagi** [comment]
NSObject `initialize` (not to confuse with `init`) is called only once per class. This is called before an actual object of this class is created. This means that selectors are generated for a specific class only once. I assume that the current approach is for performance reasons and that getting all the selectors can be expensive. If it is not true, then it's worth considering moving it into `init` and storing the result inside the proxy.

**Comment by henrimagi** [comment]
I removed the ui-tests.

**Comment by freak4pc** [comment]
@kevinrenskers do you mind trying out this branch?

**Comment by kevinrenskers** [comment]
I'm sorry but I'm too busy finishing up a project to test this, plus I already removed basically all the delegate-related publishers due to these problems.

I did share a repro project in https://github.com/CombineCommunity/CombineCocoa/issues/31 that you could try?

**Comment by henrimagi** [comment]
Any updates? I would also like this bug to be fixed ASAP.

**Comment by kevinrenskers** [comment]
Also wondering what the holdup is. Can we get this merged, please?

**Comment by freak4pc** [comment]
TBH I was hoping for a bit of help testing this. It's a bit funny pressing for this to be merged but not having a single second to assist with making sure this fix is good @kevinrenskers :) 

I'll try going over this today.

**Review by freak4pc — APPROVED** [review]

**Comment by kevinrenskers** [comment]
I see your point, but 25 days ago I did say I don't have time, and I did provide a repro project. I do have time now, but I don't think it's my fault that nothing happened in the past 25 days. 

Anyway, thanks for the fix and the merge!

**Comment by freak4pc** [comment]
It's not a matter of fault. I'm a single person and this project is a work of love, not necessity or any payment. My team and my own daily work takes a lot out of my time and I didn't have any time testing this code. 

If it would've been something blocking me (or would be trivial to review) I would've obviously carved the time to test it.

**Comment by kevinrenskers** [comment]
Well I'm in the same boat. Running a company, finishing projects, managing people. I did provide a repro project and after that didn't have time to devote to this issue. 

And since I removed all the delegate proxies from my project it wasn't blocking me.

But I have more time now so can at least help with the emoji bug 👍

**Comment by freak4pc** [comment]
I appreciate it.

**Pull request merged**
