### PR TITLE
Add `UITextView.valuePublisher`

### LINKED ISSUE #19: How can I add a textPublisher to UITextView?
Since `UITextView` doesn't subclass `UIControl` I can't just do something like this 

```
public extension UITextView {
    /// A publisher emitting any text changes to a this text field.
    var textPublisher: AnyPublisher<String?, Never> {
        Publishers.ControlProperty(control: self, events: [.allEditingEvents, .valueChanged], keyPath: \.text)
                  .eraseToAnyPublisher()
    }
}
```

So how would you add such a publisher?

### PR DESCRIPTION
**Pull request by freak4pc**
This PR adds support for a `UITextView.valuePublisher` publisher based on the one in RxCocoa and NSTextStorage (based on @jdisho's delegate proxy support).

Closes #19

### CODE REVIEW

**Comment by freak4pc** [comment]
Uhm this works fine under Xcode 11 but crashes in 12. 
image

@jdisho any thoughts before I dig into it? :]

**Comment by jdisho** [comment]
Hmm.. interesting 🤔 
I will have a look into this @freak4pc

**Comment by freak4pc** [comment]
Thanks a ton @jdisho ❤️

**Comment by jdisho** [comment]
Can this wait a bit more? I've been quite busy recently 😔

**Comment by freak4pc** [comment]
Generally, sure, but I’m waiting on this to release a version because I don’t want to cut a release that’s crashing potentially :P

Thank you very much.

Shai

**Comment by freak4pc** [comment]
Hey @jdisho, any chance you have a moment to look here?

**Comment by jdisho** [comment]
Yes @freak4pc, I will try to find the time this weekend. I am so sorry for this delay 🙏

**Comment by jdisho** [comment]
No worries, I haven't forgotten! ☺️

**Comment by freak4pc** [comment]
Looking forward. Thank you! :)

**Comment by freak4pc** [comment]
@jdisho sorry for pinging all the time, I know how busy you are :) Just want to make sure you remember it ^_^

**Comment by freak4pc** [comment]
@jdisho I believe I've mostly resolved this. The crash was resolved in Xcode 12 GM, but for some reason you've sent a `.finished` event on the subscriber whenever a single event was published. 

This was masked by the tests, but in reality these publishers are "infinite" (should only send completion on deallocation of the delegate).

**Pull request merged**
