### PR TITLE
Restructure project for SPM & Objective-C target

### PR DESCRIPTION
**Pull request by freak4pc**
It's not possible to mix Objective-C and Swift in a single SPM target. 

It is also not possible to have cyclical dependencies - like we had before, where `ObjCDelegateProxy` and `ObjcDelegateProxy+Selectors.swift` depended on each other.

To resolve this, I've moved `ObjCDelegateProxy` into its own SPM Target and rewrote `ObjCDelegateProxy+Selectors.swift` as Objective-C to get rid of the cyclical dependency. 

This means that:
1. SPM finally works well
2. We can support static and dynamic linking for CocoaPods which was an issue before that
3. I still hate Carthage but this should make it a bit easier to vend for it as well

### CODE REVIEW

**Comment by freak4pc** [comment]
FYI @jdisho

**Comment by cliss** [comment]
@freak4pc Remind me to fight with you about this offline sometime. 😆 
> I still hate Carthage but this should make it a bit easier to vend for it as well

**Comment by freak4pc** [comment]
What's this ... offline ... you're referring to ? (Covid reality) @cliss

**Comment by cliss** [comment]
oh

**Pull request merged**
